[program:code-server]
command=prlimit --rss=1073741824 code-server --config /root/.config/code-server/config.yaml /app
directory=/app
autostart=false
autorestart=true
environment=PASSWORD="1b3c1b71"
stderr_logfile=/var/log/supervisor/code-server.err.log
stdout_logfile=/var/log/supervisor/code-server.out.log
priority=999
startsecs=5