[program:nginx-code-proxy]
command=/usr/sbin/nginx -g "daemon off;" -c /etc/nginx/nginx-code-server.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx-proxy.err.log
stdout_logfile=/var/log/supervisor/nginx-proxy.out.log
priority=5
startsecs=2
stopwaitsecs=10
